export const DEPARTMENTS = [
  "Partners",
  "Sales",
  "Engineering",
  "Product",
  "Marketing",
  "People / HR",
  "Finance / Operations",
  "Customer Success",
  "Other",
] as const;

export type Department = (typeof DEPARTMENTS)[number];

export const ROLES_BY_DEPARTMENT: Record<Department, string[]> = {
  Partners: [
    "PAE (Partner Account Executive)",
    "PBD (Partner Business Development)",
    "Partner Marketing Manager",
    "Partner Ops",
    "Partner Strategy",
    "Partner CRM",
    "Partner AI / Automation",
    "Partner Onboarding Specialist",
    "Partner Integration Manager",
    "Head of Partners",
    "VP Partnerships",
  ],
  Sales: [
    "SDR (Sales Development Rep)",
    "BDR (Business Development Rep)",
    "Account Executive (AE)",
    "Senior Account Executive",
    "Sales Manager",
    "Head of Sales",
    "Sales Ops",
    "Revenue Ops",
    "Sales Engineer",
    "VP Sales",
  ],
  Engineering: [
    "Frontend Engineer",
    "Backend Engineer",
    "Full-Stack Engineer",
    "Mobile Engineer",
    "DevOps / SRE",
    "QA Engineer",
    "Data Engineer",
    "ML Engineer",
    "Staff Engineer",
    "Engineering Manager",
    "VP Engineering",
    "CTO",
  ],
  Product: [
    "Product Manager",
    "Senior Product Manager",
    "Head of Product",
    "Product Designer",
    "UX Researcher",
    "Product Analyst",
    "Product Ops",
    "CPO",
  ],
  Marketing: [
    "Content Manager",
    "Demand Gen Manager",
    "Growth Marketing Manager",
    "Event Manager",
    "Brand Manager",
    "Marketing Ops",
    "Social Media Manager",
    "SEO / SEM Specialist",
    "Head of Marketing",
    "CMO",
  ],
  "People / HR": [
    "People Partner",
    "Talent Acquisition Specialist",
    "Recruiter",
    "People Ops",
    "Compensation & Benefits",
    "People Analytics",
    "Employer Branding",
    "Head of People",
    "VP People",
    "CHRO",
  ],
  "Finance / Operations": [
    "Finance Analyst",
    "Controller",
    "FP&A Manager",
    "Legal Counsel",
    "Ops Manager",
    "Business Analyst",
    "Procurement",
    "Head of Finance",
    "CFO",
    "COO",
  ],
  "Customer Success": [
    "Customer Success Manager (CSM)",
    "Senior CSM",
    "Onboarding Specialist",
    "Implementation Manager",
    "Support Specialist",
    "Technical Support Engineer",
    "Head of Customer Success",
    "VP Customer Success",
  ],
  Other: [],
};
