export const MOCK_USER = {
  id: "mock-user-1",
  name: "Guillem Catalan",
  email: "guillem@factorial.co",
  linkedin_url: "https://www.linkedin.com/in/guillem-catalan-6085a52ab",
  department: "Partners",
  created_at: "2026-05-15T10:00:00Z",
};

export const MOCK_FEED_POSTS = [
  {
    id: "post-1",
    user_id: "mock-user-2",
    input_idea: "Closing enterprise deals in DACH region",
    variant_1: "",
    variant_2: "",
    variant_3: "",
    selected_variant: 1,
    status: "published" as const,
    published_at: "2026-05-18T14:30:00Z",
    created_at: "2026-05-18T14:00:00Z",
    published_text:
      "6 months ago we had zero clients in Germany.\n\nToday we just signed our 12th enterprise account in the DACH region.\n\nNo local office. No native German speakers on the team. No brand recognition in the market.\n\nHere's what actually worked:\n\nWe stopped translating our Spanish pitch deck into German and started building a completely new narrative around compliance — because that's what German HR leaders lose sleep over.\n\nWe partnered with 3 local payroll providers instead of trying to compete with them. They became our best referral channel.\n\nWe hired one person. Not a sales rep — a customer success manager who spoke German and understood Betriebsrat dynamics.\n\nThe deals didn't close because of our product features. They closed because we showed up understanding their problems before pitching our solution.\n\nB2B expansion isn't about translating what works at home. It's about rebuilding your go-to-market from the buyer's perspective.\n\nWhat's the hardest market your team has cracked? I'd love to compare notes.\n\n#SaaS #B2BExpansion #DACH #HRTech #Factorial",
    user: {
      name: "Marc Rivera",
      department: "Sales",
    },
    engagement: { likes: 284, comments: 47, views: 12400 },
  },
  {
    id: "post-2",
    user_id: "mock-user-3",
    input_idea: "Why we rebuilt our permissions system",
    variant_1: "",
    variant_2: "",
    variant_3: "",
    selected_variant: 1,
    status: "published" as const,
    published_at: "2026-05-17T09:15:00Z",
    created_at: "2026-05-17T09:00:00Z",
    published_text:
      "Last quarter we threw away 8 months of work on our permissions system.\n\nNot because it was buggy. Not because it was slow.\n\nBecause nobody could explain how it worked.\n\nOur engineering team had built a beautiful, flexible RBAC system with inheritance, wildcards, and contextual overrides. Technically impressive. The kind of system you'd write a blog post about.\n\nBut when a customer success manager needed to answer \"why can't this user see their payslips?\" — it took an engineer 30 minutes to trace through the permission chain.\n\nThat's a system that works for engineers, not for the business.\n\nSo we rebuilt it. Simpler. Flatter. With a rule: if you can't explain a permission decision in one sentence, the model is wrong.\n\nThe new system has fewer features. It doesn't support everything the old one did. Some edge cases need manual workarounds.\n\nBut any CS agent can now debug a permission issue in 2 minutes. Without Slack-ing an engineer. Without escalating a ticket.\n\nSoftware isn't just code. It's the decisions you make about who needs to understand it.\n\n#Engineering #ProductDesign #SaaS #Factorial",
    user: {
      name: "Laura Chen",
      department: "Engineering",
    },
    engagement: { likes: 412, comments: 63, views: 18200 },
  },
  {
    id: "post-3",
    user_id: "mock-user-4",
    input_idea: "The partner onboarding playbook",
    variant_1: "",
    variant_2: "",
    variant_3: "",
    selected_variant: 1,
    status: "published" as const,
    published_at: "2026-05-16T11:00:00Z",
    created_at: "2026-05-16T10:30:00Z",
    published_text:
      "We onboarded 40 new partners last quarter.\n\n12 of them generated revenue in their first month. The other 28 went silent.\n\nSame product. Same training. Same support. Different results.\n\nI spent two weeks calling every single partner who went quiet. Not to sell them anything — just to understand what happened.\n\nThe pattern was clear: the partners who succeeded had one thing in common. They didn't try to sell Factorial as an HR tool.\n\nThey positioned it as the solution to a specific pain their clients already complained about. Payroll errors. Time tracking chaos. Onboarding that takes 3 weeks instead of 3 days.\n\nThe silent partners? They'd added us to their portfolio, put our logo on their website, and waited for inbound.\n\nPartner success isn't about enablement decks and certification programs. It's about helping partners connect your product to conversations they're already having.\n\nNow our onboarding starts with one question: \"What's the #1 complaint your clients have about HR?\"\n\nEverything else follows from that answer.\n\n#Partnerships #B2B #ChannelSales #HRTech #Factorial",
    user: {
      name: "Guillem Catalan",
      department: "Partners",
    },
    engagement: { likes: 198, comments: 31, views: 8900 },
  },
  {
    id: "post-4",
    user_id: "mock-user-5",
    input_idea: "Employer branding when you can't compete on salary",
    variant_1: "",
    variant_2: "",
    variant_3: "",
    selected_variant: 1,
    status: "published" as const,
    published_at: "2026-05-15T16:45:00Z",
    created_at: "2026-05-15T16:00:00Z",
    published_text:
      "We lost 3 candidates to Google last month.\n\nSame week, we hired 2 people who turned down Amazon offers to join us.\n\nThe difference wasn't compensation. Google and Amazon both paid more.\n\nThe difference was that the 2 people who chose us had talked to someone on our team before applying. A real conversation. Not a recruiter pitch — an honest chat about what it's actually like to work here.\n\nOne of them told me: \"I could tell within 10 minutes that your team actually cares about the product they're building. At the other place, everyone talked about their career path.\"\n\nEmployer branding isn't your careers page. It isn't your Glassdoor rating. It isn't your LinkedIn posts about culture.\n\nIt's what your employees say when they're not being watched.\n\nThe best thing we ever did for hiring wasn't a campaign. It was making the work genuinely interesting and then letting people talk about it naturally.\n\nYou can't fake that. And candidates can always tell when you're trying.\n\n#Hiring #EmployerBranding #Talent #HRTech #Factorial",
    user: {
      name: "Ana Rodríguez",
      department: "People / HR",
    },
    engagement: { likes: 523, comments: 89, views: 24100 },
  },
  {
    id: "post-5",
    user_id: "mock-user-6",
    input_idea: "Customer success metrics that actually matter",
    variant_1: "",
    variant_2: "",
    variant_3: "",
    selected_variant: 1,
    status: "published" as const,
    published_at: "2026-05-14T13:20:00Z",
    created_at: "2026-05-14T13:00:00Z",
    published_text:
      "Our NPS was 72 last quarter.\n\nWe also lost our biggest client.\n\nThey'd been a promoter for 3 consecutive surveys. Score of 9 or 10 every time. The kind of client you put in case studies.\n\nThen their new CFO asked a simple question: \"What's the ROI of this tool?\" And nobody on their team could answer it.\n\nNPS measures sentiment. It doesn't measure value delivery. A client can love your product and still not be able to justify it when budgets get cut.\n\nWe've since added one metric to every quarterly review: can the client articulate, in their own words, the business impact of using Factorial?\n\nNot our talking points. Their words. Their numbers.\n\nIf they can't, it doesn't matter what score they give us. We're one reorg away from losing them.\n\nRetention isn't about making clients happy. It's about making them successful in ways they can prove to their leadership.\n\nWhat's your team's leading indicator for churn risk?\n\n#CustomerSuccess #SaaS #Retention #Metrics #Factorial",
    user: {
      name: "David Park",
      department: "Customer Success",
    },
    engagement: { likes: 347, comments: 58, views: 15600 },
  },
];

export const MOCK_MY_POSTS = [
  {
    id: "my-post-1",
    input_idea: "We onboarded 40 new partners last quarter",
    status: "published" as const,
    published_at: "2026-05-16T11:00:00Z",
    created_at: "2026-05-16T10:30:00Z",
    selected_variant: 1,
    preview: "We onboarded 40 new partners last quarter. 12 of them generated revenue in their first month...",
    engagement: { likes: 198, comments: 31, views: 8900 },
  },
  {
    id: "my-post-2",
    input_idea: "How we structure partner tiers",
    status: "draft" as const,
    published_at: null,
    created_at: "2026-05-19T09:00:00Z",
    selected_variant: null,
    preview: "Not every partner deserves the same level of support. Controversial? Maybe. But here's what we learned...",
    engagement: null,
  },
  {
    id: "my-post-3",
    input_idea: "Lessons from our first partner event in London",
    status: "published" as const,
    published_at: "2026-05-10T14:00:00Z",
    created_at: "2026-05-10T13:00:00Z",
    selected_variant: 2,
    preview: "50 people in a room in Shoreditch. Half of them had never heard of Factorial...",
    engagement: { likes: 142, comments: 23, views: 6300 },
  },
];
